---
- name: Converge
  hosts: localhost
  tasks:
    - name: Start Converge Task
      debug:
        msg: "Converge Task"

- name: Import setup.yml playbook
  import_playbook: ../../playbooks/setup.yml
