---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    cleanup: cleanup.yml
    converge: converge.yml
    idempotence: idempotence.yml
    verify: verify.yml
verifier:
  name: ansible

scenario:
  test_sequence:
    - syntax
    - create
    - converge
    - verify
    - idempotence
    - cleanup
    - destroy
