---
- name: Clean Lava RPC Provider
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:

    - name: Stop and remove service
      service:
        name: "{{ lava_service_name }}"
        state: stopped
        enabled: false
      ignore_errors: true

    - name: Remove Lava Provider user
      user:
        name: "{{ lava_user }}"
        state: absent
        remove: true

    - name: Remove Lava Provider group
      group:
        name: "{{ lava_group }}"
        state: absent

    - name: Remove binary
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "/usr/local/bin/{{ lava_binary.name }}"

    - name: Remove install directory
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ lava_install_dir }}"
