---
- name: Setup Lava RPC Provider
  hosts: localhost
  become: true
  vars_files:
    - ../group_vars/all.yml
  roles:
    - role: ../roles/provider
  environment:
    LAVA_BINARY: "{{ lava_binary.name }}"
